name: Build and deploy Node.js app to Azure Web App - aicareercoach

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Generate Prisma
      - name: Generate Prisma Client
        run: npx prisma generate
        
      - name: Push Prisma schema to DB
        run: npx prisma db push
      # Build Next.js app
      - name: Build app
        run: npm run build

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B7CF852BDDE4F218BCE8330FF513FA0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D606307F25D44824B42CA9AF3094A920 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5F7A5EBFE9B34F009030A9699F8B06C8 }}

      # Deploy directly (IMPORTANT)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aicareercoach'
          slot-name: 'Production'
          package: .
